GET http://localhost:5000/api/v1/users

###

POST http://localhost:5000/private/api/rooms?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxZDVjOTc0ZjU1YmIwNDg4YzlmNmYwYSIsImVtYWlsIjoidGVzdDJAdGVzdC5jb20ifSwiaWF0IjoxNjQxNDczNTgxfQ.hEY5lXe5EXMitNVT0c9zdesYW3v7XMbVuYeY-Tst71c HTTP/1.1
content-type: application/json

{
  "name": "Secret room"
}

###

GET http://localhost:5000/api/rooms/5fa025e6a1da8a6194838d5f

###

PATCH http://localhost:5000/api/rooms/5fa025e6a1da8a6194838d5f HTTP/1.1
content-type: application/json

{
  "name": "Basique"
}

###

POST http://localhost:5000/api/v1/users HTTP/1.1
content-type: application/json

{
    "password": "testtheo",
    "firstName_u": "testtheo",
    "lastName_u": "testtheo",
    "company_u": "testtheo",
    "siret_u": "testtheo",
    "address_u": "testtheo",
    "phone_u": "0214761476",
    "email": "theo@hotmail.fr",
    "role_id": "61d859ce6d4d8a47389c6caf"
}  

###

POST http://localhost:5000/api/v1/roles HTTP/1.1
content-type: application/json

{
    "name_r": "client",
    "description_r": "client de l'entreprise",
    "key_r": "3"
}

###

POST http://localhost:5000/login HTTP/1.1
content-type: application/json

{
  "email": "test2@test.com",
  "password": "test"
}

###

GET http://localhost:5000/private/secret?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxZDVjOTc0ZjU1YmIwNDg4YzlmNmYwYSIsImVtYWlsIjoidGVzdDJAdGVzdC5jb20ifSwiaWF0IjoxNjQxNDczNTgxfQ.hEY5lXe5EXMitNVT0c9zdesYW3v7XMbVuYeY-Tst71c

###

POST http://localhost:5000/api/v1/roles HTTP/1.1
content-type: application/json

{    
  "name_r": "Directeur",
  "description_r": "Propriétaire de l'entreprise"
}

###

DELETE http://localhost:5000/api/v1/users/61d854ea9b65dc42501b08bc HTTP/1.1
content-type: application/json

### CREATE A NEW DRONE IN DATABASE

POST http://localhost:5000/api/v1/drone/ HTTP/1.1
Content-Type: application/json

{
    "name": "DJI ALLTESTTheo",
    "category": "Pro",
    "description": "New",
    "pricePerDay": "690"
}

### GET ALL DRONES

GET http://localhost:5000/api/v1/drones/ HTTP/1.1
Content-Type: application/json

### GET ONE DRONE

GET http://localhost:5000/api/v1/drones/61f263fd7568824e10a31023 HTTP/1.1
Content-Type: application/json

### PATCH A DRONE

PATCH http://localhost:5000/api/v1/drones/61f263fd7568824e10a31023 HTTP/1.1
Content-Type: application/json

{
    "name": "DJI NEWNAME",
    "category": "Pro",
    "description": "New Price for this drone",
    "pricePerDay": "759"
}

### DELETE A DRONE

DELETE http://localhost:5000/api/v1/drones/61f7a09663f9a55f20056916 HTTP/1.1
Content-Type: application/json