### GET ALL USERS

GET http://localhost:5000/api/v1/users/ HTTP/1.1
content-type: application/json

###

### GET ONE USER

GET http://localhost:5000/api/v1/users/61f7dacb6301b33554b5da01 HTTP/1.1
content-type: application/json

###

### CREATE USER

POST http://localhost:5000/signup HTTP/1.1
content-type: application/json

{
    "password": "passwordtest",
    "firstName_u": "posttheo",
    "lastName_u": "posttheo",
    "company_u": "posttheo",
    "siret_u": "posttheo",
    "address_u": "postelehavre",
    "phone_u": "0214761476",
    "email": "postth5@hotmail.fr",
    "role_id": "61d859ce6d4d8a47389c6caf"
}

###

### PATCH USER
PATCH http://localhost:5000/api/v1/users/61f7dafd6301b33554b5da05 HTTP/1.1
content-type: application/json

{
    "password": "passwordtest",
    "firstName_u": "updatetheo",
    "lastName_u": "updatetheo",
    "company_u": "updatetheo",
    "siret_u": "updatetheo",
    "address_u": "updatetheo",
    "phone_u": "0214761476",
    "email": "theoupdate@hotmail.fr",
    "role_id": "61d859ce6d4d8a47389c6caf"
}

###

### DELETE USER
DELETE http://localhost:5000/api/v1/users/61f7dafd6301b33554b5da05 HTTP/1.1
content-type: application/json

###

### GET ALL CATEGORIES

GET http://localhost:5000/api/v1/categories/ HTTP/1.1
content-type: application/json

###

### GET ONE CATEGORY

GET http://localhost:5000/api/v1/categories/61f7de6c85047e33dc40bee0 HTTP/1.1
content-type: application/json

###

### CREATE CATEGORY

POST http://localhost:5000/api/v1/categories/ HTTP/1.1
content-type: application/json

{
    "name_cat": "First Category TEST",
    "description_cat": "Category TEST",
    "key_cat": "1"
}

###

### PATCH CATEGORY

PATCH http://localhost:5000/api/v1/categories/61f7de6c85047e33dc40bee0 HTTP/1.1
content-type: application/json

{
    "name_cat": "Update Category TEST",
    "description_cat": "Update Category TEST",
    "key_cat": "1"
}

###

### DELETE CATEGORY

DELETE http://localhost:5000/api/v1/categories/61f7de6c85047e33dc40bee0 HTTP/1.1
content-type: application/json

###

### GET ALL ROLES

GET http://localhost:5000/api/v1/roles/ HTTP/1.1
content-type: application/json

###

### GET ONE DRONE

GET http://localhost:5000/api/v1/roles/61d859366d4d8a47389c6cab HTTP/1.1
content-type: application/json

###

### CREATE ROLE

POST http://localhost:5000/api/v1/roles HTTP/1.1
content-type: application/json

{
    "name_r": "DEVTEST",
    "description_r": "DeveloppeurTEST",
    "key_r": "4"
}

###

### PATCH ROLE

PATCH http://localhost:5000/api/v1/roles/61f7d8ea5a62ae13580c2dfe HTTP/1.1
content-type: application/json

{
    "name_r": "DEV TESTEUR",
    "description_r": "Developpeur pour un test",
    "key_r": "4"
}

###

### DELETE ROLE

DELETE http://localhost:5000/api/v1/roles/61f7d8ea5a62ae13580c2dfe HTTP/1.1
content-type: application/json

###

### GET ALL DRONES

GET http://localhost:5000/api/v1/drones/ HTTP/1.1
Content-Type: application/json

###

### GET ONE DRONE

GET http://localhost:5000/api/v1/drones/61fa3ffbcd584b1ab0f97e01 HTTP/1.1
Content-Type: application/json

###

### CREATE DRONE

POST http://localhost:5000/api/v1/drones/ HTTP/1.1
Content-Type: application/json

{
    "name_d": "TEST JB DON'T DELETE",
    "category_id": "61f7de6c85047e33dc40bee0",
    "description_d": "New Super 8",
    "pricePerDay_d": "320"
}

###

### PATCH DRONE

PATCH http://localhost:5000/api/v1/drones/61fa3ffbcd584b1ab0f97e01 HTTP/1.1
Content-Type: application/json

{
    "name_d": "DJI TODELETE",
    "category_id": "61f7de6c85047e33dc40bee0",
    "description_d": "New Price for this drone",
    "pricePerDay_d": "200",
    "processState_id": "61fa80c3de01110590c87c5a"
}

###

### DELETE DRONE

DELETE http://localhost:5000/api/v1/drones/61f263fd7568824e10a31023 HTTP/1.1
Content-Type: application/json

###

### LOGIN

POST http://localhost:5000/login HTTP/1.1
content-type: application/json

{
  "email": "test2@test.com",
  "password": "test"
}

###

### GET DRONE BY CATEGORY

GET http://localhost:5000/api/v1/drones/category/61f7de6c85047e33dc40bee0 HTTP/1.1
content-type: application/json

###

### ADD Process State

POST http://localhost:5000/api/v1/ps HTTP/1.1
Content-Type: application/json

{
    "name_ps": "Disponible",
    "description_ps": "Le drone est disponible"
}

###

### GETALL Process State

GET http://localhost:5000/api/v1/ps HTTP/1.1
Content-Type: application/json

